[package]
name = "swayboard"
version = "0.1.0"
authors = ["Belousow Makc <lib.bmw@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swayipc-async = "2.0.0-alpha.2"
swayipc-types = "1.0.0-alpha.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.8"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
